name: scannenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2
  - flask
  - pandas
  - numpy
  - scipy
  - tensorflow=2.18.0
  - pythonocc-core
  - pip
  - pip:
    - <any extra pip-only packages>